### ISSUE TITLE
Character 界 not recognized as letter (and similar)

### ISSUE THREAD

**Issue by daschl** [swgillespie/unicode-categories#3]
Hi,

According to this page https://codepoints.net/U+754C I think the character  界 is a letter, but it is not recognized as such:

``` rust
extern crate unicode_categories;

use unicode_categories::UnicodeCategories;
fn main() {
    let input = "界";
    println!("{:?}", input.len());
    println!("{:?}", input.chars().count());
    for ch in input.chars() {
        println!("ch = {:?} {:x} {:?}", ch.is_letter(), ch as u32, ch);
    }
}
```

```
3
1
ch = false 754c '\u{754c}'
```

I see that the mapping is generated from the UnicodeData file, but I don't think its in there - do you know why and what we could do that it correctly identifies as a letter? Did I understand something wrong on how the mapping is supposed to work?

Thanks!
Michael

**Comment by daschl** [comment]
@swgillespie let me know if there is anything I can help fixing if needs to be fixed at all.

**Comment by daschl** [comment]
Oh wait, it looks like this is an ideograph that is defined as a range (!) in the unicodedata.txt file:

```
4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
9FD5;<CJK Ideograph, Last>;Lo;0;L;;;;;N;;;;;
```

and it just plainly maps to them without a range (?) https://github.com/swgillespie/unicode-categories/blob/master/src/tables.rs#L764

**Comment by swgillespie** [comment]
@daschl I'm happy to take a PR if something's wrong! I auto-generated the rust tables directly from [UnicodeData.txt](ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt), so feel free to modify the script if it should be doing something other than what it does.

**Comment by daschl** [comment]
@swgillespie heh yeah I'll see what I can get done.. the thing is in this case the unicodedata.txt specifies a range, not a code point (see my comment above), so either we generate a code point for every element in the range or add some special logic that the lookup notices its "in the range".

**Comment by swgillespie** [comment]
Makes sense. I'll admit that I'm not familiar enough with the depths of unicode to know the implications of that - this crate was born out of the need for a ECMAScript lexer to look up individual non-range characters that are allowed in identifiers. The script that the Rust compiler uses to generate its unicode tables is much more thorough (https://github.com/rust-lang/rust/blob/master/src/etc/unicode.py) so perhaps it handles this case correctly already?

It also generates much more sophisticated and efficient code so perhaps the future of this crate could be simply copying what rustc does.

**Comment by daschl** [comment]
Just for reference, in the UnicodeData.txt I think these are ranges that have First/Last markers:

```
3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;
4DB5;<CJK Ideograph Extension A, Last>;Lo;0;L;;;;;N;;;;;

4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
9FD5;<CJK Ideograph, Last>;Lo;0;L;;;;;N;;;;;

AC00;<Hangul Syllable, First>;Lo;0;L;;;;;N;;;;;
D7A3;<Hangul Syllable, Last>;Lo;0;L;;;;;N;;;;;

D800;<Non Private Use High Surrogate, First>;Cs;0;L;;;;;N;;;;;
DB7F;<Non Private Use High Surrogate, Last>;Cs;0;L;;;;;N;;;;;
DB80;<Private Use High Surrogate, First>;Cs;0;L;;;;;N;;;;;
DBFF;<Private Use High Surrogate, Last>;Cs;0;L;;;;;N;;;;;
DC00;<Low Surrogate, First>;Cs;0;L;;;;;N;;;;;
DFFF;<Low Surrogate, Last>;Cs;0;L;;;;;N;;;;;
E000;<Private Use, First>;Co;0;L;;;;;N;;;;;
F8FF;<Private Use, Last>;Co;0;L;;;;;N;;;;;

17000;<Tangut Ideograph, First>;Lo;0;L;;;;;N;;;;;
187EC;<Tangut Ideograph, Last>;Lo;0;L;;;;;N;;;;;

20000;<CJK Ideograph Extension B, First>;Lo;0;L;;;;;N;;;;;
2A6D6;<CJK Ideograph Extension B, Last>;Lo;0;L;;;;;N;;;;;
2A700;<CJK Ideograph Extension C, First>;Lo;0;L;;;;;N;;;;;
2B734;<CJK Ideograph Extension C, Last>;Lo;0;L;;;;;N;;;;;
2B740;<CJK Ideograph Extension D, First>;Lo;0;L;;;;;N;;;;;
2B81D;<CJK Ideograph Extension D, Last>;Lo;0;L;;;;;N;;;;;
2B820;<CJK Ideograph Extension E, First>;Lo;0;L;;;;;N;;;;;
2CEA1;<CJK Ideograph Extension E, Last>;Lo;0;L;;;;;N;;;;;

F0000;<Plane 15 Private Use, First>;Co;0;L;;;;;N;;;;;
FFFFD;<Plane 15 Private Use, Last>;Co;0;L;;;;;N;;;;;
100000;<Plane 16 Private Use, First>;Co;0;L;;;;;N;;;;;
10FFFD;<Plane 16 Private Use, Last>;Co;0;L;;;;;N;;;;;
```

**Comment by daschl** [comment]
@swgillespie I took a stab at this in #4 and the test passed, but of course this adds quite some entries to the tables. its probably not super bad since we are doing binary search I think.

The only other way would be to add logic and match for those ranges, but then of course its decoupled from the unicode file and maybe get outdated.

**Comment by daschl** [comment]
Actually you know what adding this huge table is just too wasteful, I'll do a new PR simple range checks, its not that much and for sure more efficient.

**Comment by daschl** [comment]
@swgillespie okay check out #5, even if its hardcoded I think its worth the tradeoff to not have the huge table and honest I don't think the ranges will change that often :)

**Comment by daschl** [comment]
@swgillespie thanks - if you get a chance can you slice a 0.1.1? Not sure when I get to the optimizations but depending on the bugfix would be great - thanks!

**Comment by swgillespie** [comment]
@daschl done!

**Comment by daschl** [comment]
Thanks!
